# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  # Triggers the workflow when a release is created
  release:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install prerequisites
      run: |
          sudo wget https://dl.min.io/client/mc/release/linux-amd64/mc && \
          sudo chmod +x mc && \
          sudo mv mc /usr/local/bin/mc
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -f projects/HiveListenerExample/pom.xml assembly:assembly
    - name: Push to S3
      run: |
          ls .
          mc alias set s3 ${{ secrets.AWS_S3_ENDPOINT }} ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          mc cp ./target/HiveListener-0.0.1-jar-with-dependencies.jar s3/projet-onyxia/build/hive-listener/hive-listener-${{ github.event.release.tag_name }}.jar
